name: client
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04 # 배포 실행될 환경
    steps: #각 단계의 이름과 실행내용을 나열해서 작성한다.
      - name: Checkout source code.
        uses: actions/checkout@v2 

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # 사용할 Node.js 버전

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Set up AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.ACCESSKEYID }}
          aws configure set aws_secret_access_key ${{ secrets.SECRETEACCESSKEY }}
          aws configure set default.region ap-northeast-2 

      - name: Build
        run: npm install && npm run build # 프로젝트 빌드

      - name: Sync to S3
        run: aws s3 sync ./dist s3://wowyoutoofront --delete # 변경 사항을 S3에 동기화